name: Light build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish framework dependent
      run: dotnet publish /p:PublishProfile=net-6.0-windows-x64-framework-dependent.pubxml
    
    - name: Create installer for framework dependent
      run: iscc Installer/Installer.iss

    - name: Upload framework dependent
      uses: actions/upload-artifact@v4
      with:
        name: net-6.0-windows-x64-framework-dependent
        path: FfmpegVideoMerger/bin/publish/Release/net6.0-windows-x64-framework-dependent/FfmpegVideoMerger.exe
        if-no-files-found: error

    - name: Upload installer for framework dependent
      uses: actions/upload-artifact@v4
      with:
        name: net-6.0-windows-x64-framework-dependent-installer
        path: Installer/Output/net6.0-windows-x64-framework-dependent.exe
        if-no-files-found: error